### ISSUE TITLE
Add an option to hide errors

### ISSUE THREAD

**Issue by kaipee** [jfrog/log4j-tools#10]
Running scan_log4j_versions.py against the root directory generates tonnes of output for unopened files.

```
/usr/bin/python3 scan_log4j_versions.py /
Scanning /
snap/core18/2246/usr/share/doc/apparmor/changelog.Debian.gz: file could not be opened successfully
[Errno 2] No such file or directory: '/snap/core18/2246/usr/share/doc/bash/README.md.bash_completion.gz'
snap/core18/2246/usr/share/doc/bash/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/bash-completion/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/bsdutils/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/bzip2/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/cloud-guest-utils/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/cloud-init/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/coreutils/changelog.Debian.gz: file could not be opened successfully
snap/core18/2246/usr/share/doc/dash/changelog.Debian.gz: file could not be opened successfully
...
```

Please add an option to hide/disable errors on output.

**Comment by ilya-k-1** [comment]
Added `-quiet` flag in the latest commit.
Also changed the output format, so that you can filter out the interesting lines only with `| grep ">>"`

**Comment by kaipee** [comment]
Thanks, works fine except on a few systems which return error:

```python3 scan_log4j_versions.py / -quiet
Traceback (most recent call last):
  File "scan_log4j_versions.py", line 4, in <module>
    from enum import Enum, IntEnum, auto
ImportError: cannot import name 'auto'
```

**Comment by ilya-k-1** [comment]
Could you run `python --version` on those systems?
In any case, one quick fix you can try is using scan_log4j_version_p2.py instead (it's a python 2 port, but it also works with python 3). Would not recommend working with it always, it may be slower in some cases.

**Comment by kaipee** [comment]
```
python --version
Python 2.7.6

python3 --version
Python 3.4.3

python3 scan_log4j_versions.py / -quiet
Traceback (most recent call last):
  File "scan_log4j_versions.py", line 4, in <module>
    from enum import Enum, IntEnum, auto
ImportError: cannot import name 'auto'

python scan_log4j_versions_p2.py --quiet
Traceback (most recent call last):
  File "scan_log4j_versions_p2.py", line 4, in <module>
    from enum import Enum, IntEnum
ImportError: No module named enum

```

**Comment by ilya-k-1** [comment]
Have to say it's a little puzzling, but I'll test with these versions precisely.
Did you try 
python3 scan_log4j_versions_p2.py --quiet
?

**Comment by kaipee** [comment]
```
python3 scan_log4j_versions_p2.py --quiet
Traceback (most recent call last):
  File "scan_log4j_versions_p2.py", line 5, in <module>
    from typing import IO, Set
ImportError: No module named 'typing'
```

**Comment by ilya-k-1** [comment]
Hi @kaipee .
Great, thanks for your input!
Fixed the dependence on newer language features in latest commit, tested with python3.4.10. Let me know if it helps (both scan_log4j_versions.py and scan_log4j_versions_p2.py should work with python3.4 now). Running _p2 script in python2.7.6 is not resolved for now (requires more extensive changes)

**Comment by kaipee** [comment]
Seems to be working, many thanks!

```
wget https://raw.githubusercontent.com/jfrog/log4j-tools/main/scan_log4j_versions.py
chmod +x scan_log4j_versions.py
python3 scan_log4j_versions.py / -quiet
Scanning /
```
